name: Build and Push Components

on:
  workflow_call:
    inputs:
      git_ref:
        required: false
        type: string
        description: 'The branch, tag or SHA to build.'
        default: ''
      image_tag:
        required: true
        type: string
        description: 'Image tag to use.'
      registry_name:
        required: false
        type: string
        description: 'Name of the registry.'
        default: ghcr.io/openclarity
      suffix:
        required: false
        type: string
        description: 'Suffix to append to the image name'
        default: ''
      bake-group:
        required: false
        type: string
        description: 'Name of the Docker Bake group of targets'
        default: default
  workflow_dispatch:
    inputs:
      git_ref:
        required: false
        type: string
        description: 'The branch, tag or SHA to build.'
        default: ''
      image_tag:
        required: true
        type: string
        description: 'Image tag to use.'
        default: latest
      registry_name:
        required: false
        type: string
        description: 'Name of the registry.'
        default: ghcr.io/openclarity
      suffix:
        required: false
        type: string
        description: 'Suffix to append to the image name'
        default: '-dev'
      bake-group:
        required: false
        type: string
        description: 'Name of the Docker Bake group of targets'
        default: default

permissions:
  packages: write

jobs:
  prepare-build:
    runs-on: ubuntu-latest
    outputs:
      timestamp: ${{ steps.timestamp.outputs.timestamp }}
      targets: ${{ steps.targets.outputs.targets }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.event.inputs.git_ref }}

      - name: Set timestamp
        id: timestamp
        run: |
          ##
          ## Set timestamp variable
          ##

          echo "timestamp=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> "$GITHUB_OUTPUT"

      - name: List targets
        id: targets
        uses: docker/bake-action/subaction/list-targets@3fc70e1131fee40a422dd8dd0ff22014ae20a1f3 # v5.11.0
        with:
          target: ${{ inputs.bake-group }}

  build-and-push:
    needs: prepare-build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targets: ${{ fromJson(needs.prepare-build.outputs.targets) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf # v3.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@6524bf65af31da8d45b59e8c27de4bd072b392f5 # v3.8.0

      - name: Cache Docker layers
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to GitHub Container Registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create cache directory
        run: mkdir -p /tmp/.buildx-cache

      - name: Build
        uses: docker/bake-action@3fc70e1131fee40a422dd8dd0ff22014ae20a1f3 # v5.11.0
        id: bake
        with:
          targets: ${{ matrix.targets }}
          set: |
            *.platform=linux/amd64,linux/arm64
            *.output=type=image,name=${{ inputs.registry_name }}/${{ matrix.targets }},name-canonical=true,push=true
            *.cache-to=type=local,dest=/tmp/.buildx-cache
            *.cache-from=type=local,src=/tmp/.buildx-cache
        env:
          VERSION: ${{ inputs.image_tag }}
          BUILD_TIMESTAMP: ${{ needs.prepare-build.outputs.timestamp }}
          COMMIT_HASH: ${{ github.sha }}
          DOCKER_REGISTRY: ${{ inputs.registry_name }}
          SUFFIX: ${{ inputs.suffix }}
          DOCKER_TAG: ${{ inputs.image_tag }}
          BUILD_OPTS: -tags=exclude_graphdriver_btrfs,exclude_graphdriver_devicemapper
