name: Verification

on:
  workflow_call:

jobs:
  licenses:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Go
        uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
        with:
          # NOTE(chrisgacsal): Use actions/cache for caching Go dependency and build caches
          # as it provides better flexibility like setting the cache key which reduces cache misses significantly.
          cache: false
          go-version-file: '.go-version'

      - name: License cache
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
        with:
          path: |
            .licensei.cache
            **/.licensei.cache
          key: licensei-${{ github.ref_name }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            licensei-${{ github.ref_name }}-
            licensei-${{ github.event.repository.default_branch }}-
          save-always: true

      # Vendor deps before running https://github.com/goph/licensei
      # to avoid false-positives when modules GitHub repo could not be determined
      - name: Vendor dependencies to retrieve licenses locally
        run: make gomod-vendor

      - name: Download license information for dependencies
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make license-cache

      - name: Check licenses
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make license-check

  distributions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Cloud Formation Linter with Latest Version
        uses: scottbrenner/cfn-lint-action@b8b449ced9a89d5335b2ed60c3b3c6088af82e13 # v2.4.7

      - name: Run linters for Cloudformation
        run: make lint-cfn

      - name: Run linters for Helm
        run: |
          make gen-helm-docs
          make lint-helm
          [[ -z "$(git status --porcelain)" ]] || exit 1

      - name: Run linters for Azure/Bicep
        run: |
          make gen-bicep
          make lint-bicep
          [[ -z "$(git status --porcelain)" ]] || exit 1

  actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Lint Github workflows
        run: |
          echo "::add-matcher::.github/actionlint-matcher.json"
          make lint-actions
          echo "::remove-matcher owner=actionlint::"

  javascript:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install modules
        run: make ui-install

      - name: Run format
        run: make format-ui-check

      - name: Run ESLint
        run: make lint-js

      - name: Run tests
        run: make test-js

  go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Go
        uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
        with:
          # NOTE(chrisgacsal): Use actions/cache for caching Go dependency and build caches
          # as it provides better flexibility like setting the cache key which reduces cache misses significantly.
          cache: false
          go-version-file: '.go-version'

      - name: Free up disk space
        run: |
          df -h

          # Remove .NET related tooling
          sudo du -sh /usr/share/dotnet
          sudo rm -rf /usr/share/dotnet

          # Remove Android related tooling
          sudo du -sh /usr/local/lib/android
          sudo rm -rf /usr/local/lib/android

          # Remove CodeQL
          sudo du -sh /opt/hostedtoolcache/CodeQL
          sudo rm -rf /opt/hostedtoolcache/CodeQL

          df -h

      - name: Setup Go caching
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ github.ref_name }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ github.ref_name }}-
            ${{ runner.os }}-go-${{ github.event.repository.default_branch }}-

      - name: Install required libs and tools
        run: sudo apt-get install libbtrfs-dev libgpgme-dev pkg-config -y

      - name: Verify APIs
        run: |
          make gen-api-go
          [[ -z "$(git status --porcelain)" ]] || exit 1

      - name: Verify go modules
        run: |
          make gomod-list
          make gomod-tidy
          [[ -z "$(git status --porcelain)" ]] || exit 1

      - name: Run go vet
        run: make vet

      - name: Cache golangci-lint cache
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
        with:
          path: ${{ github.workspace }}/.golangci.cache
          key: golangci-${{ github.ref_name }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            golangci-${{ github.ref_name }}-
            golangci-${{ github.event.repository.default_branch }}-

      - name: Run linters
        env:
          GOLANGCI_LINT_CACHE: ${{ github.workspace }}/.golangci.cache
        run: make lint-go

      - name: Run tests
        run: make test-go
